[rpki]
#rsyncrepo   = "/home/user/.rpki-cache/repository/rsync"

[rpki.tals]
# Before uncommenting and using the ARIN TAL, please make sure you read and
# agree with the ARIN RPA: 
# https://www.arin.net/resources/manage/rpki/tal/#relying-party-agreement-rpa
#
#arin       = "rsync://rpki.arin.net/repository/arin-rpki-ta.cer"
#afrinic    = "rsync://rpki.afrinic.net/repository/AfriNIC.cer"
#apnic      = "rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer"
#lacnic     = "rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer"
#ripe       = "rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer"

[webservice]
port = 8081
domain = "http://localhost:8081" # NB: no trailing slash here
atlas_api_key = ""
