[rpki]
rsync_data_dir  = "rsync_repo"
rrdp_data_dir   = "rrdp_repo"
tal_dir         = "tals"

[rpki.tals]
# Before uncommenting and using the ARIN TAL, please make sure you read and
# agree with the ARIN RPA: 
# https://www.arin.net/resources/manage/rpki/tal/#relying-party-agreement-rpa

arin    = "arin.tal"
afrinic = "afrinic.tal"
apnic   = "apnic.tal"
lacnic  = "lacnic.tal"
ripe    = "ripe.tal"

#testbed     = "testbed.tal"
#ripe-local  = "ripe-local.tal"

[webservice]
port = 8081
domain = "http://localhost:8081" # NB: no trailing slash here
atlas_api_key = ""
logfile = "/tmp/jdr.log"
